from Bulbasaur import Bulbasaur
from Ivysaur import Ivysaur
from Venusaur import Venusaur
from Charmander import Charmander
from Charmeleon import Charmeleon
from Charizard import Charizard
from Squirtle import Squirtle
from Wartortle import Wartortle
from Blastoise import Blastoise
from Caterpie import Caterpie
from Metapod import Metapod
from Butterfree import Butterfree
from Weedle import Weedle
from Kakuna import Kakuna
from Beedrill import Beedrill
from Pidgey import Pidgey
from Pidgeotto import Pidgeotto
from Pidgeot import Pidgeot
from Rattata import Rattata
from Raticate import Raticate
from Spearow import Spearow
from Fearow import Fearow
from Ekans import Ekans
from Arbok import Arbok
from Pikachu import Pikachu
from Raichu import Raichu
from Sandshrew import Sandshrew
from Sandslash import Sandslash
from NidoranF import NidoranF
from Nidorina import Nidorina
from Nidoqueen import Nidoqueen
from NidoranM import NidoranM
from Nidorino import Nidorino
from Nidoking import Nidoking
from Clefairy import Clefairy
from Clefable import Clefable
from Vulpix import Vulpix
from Ninetails import Ninetails
from Jigglypuff import Jigglypuff
from Wigglytuff import Wigglytuff
from Zubat import Zubat
from Golbat import Golbat
from Oddish import Oddish
from Gloom import Gloom
from Vileplume import Vileplume
from Paras import Paras
from Parasect import Parasect
from Venonat import Venonat
from Venomoth import Venomoth
from Diglet import Diglet
from Dugtrio import Dugtrio
from Meowth import Meowth
from Persian import Persian
from Psyduck import Psyduck
from Golduck import Golduck
from Mankey import Mankey
from Primeape import Primeape
from Growlithe import Growlithe
from Arcanine import Arcanine
from Poliwag import Poliwag
from Poliwhirl import Poliwhirl
from Poliwrath import Poliwrath
from Abra import Abra
from Kadabra import Kadabra
from Alakazam import Alakazam
from Machop import Machop
from Machoke import Machoke
from Machamp import Machamp
from Bellsprout import Bellsprout
from Weepinbell import Weepinbell
from Victreebel import Victreebel
from Tentacool import Tentacool
from Tentacruel import Tentacruel
from Geodude import Geodude
from Graveler import Graveler
from Golem import Golem
from Ponyta import Ponyta
from Rapidash import Rapidash
from Slowpoke import Slowpoke
from Slowbro import Slowbro
from Magnemite import Magnemite
from Magneton import Magneton
from Farfetchd import Farfetchd
from Doduo import Doduo
from Dodrio import Dodrio
from Seel import Seel
from Dewgong import Dewgong
from Grimer import Grimer
from Muk import Muk
from Shellder import Shellder
from Cloyster import Cloyster
from Gastly import Gastly
from Haunter import Haunter
from Gengar import Gengar
from Onix import Onix
from Drowzee import Drowzee
from Hypno import Hypno
from Krabby import Krabby
from Kingler import Kingler
from Voltorb import Voltorb
from Electrode import Electrode
from Exeggcute import Exeggcute
from Exeggutor import Exeggutor
from Cubone import Cubone
from Marowak import Marowak
from Hitmonlee import Hitmonlee
from Hitmonchan import Hitmonchan
from Lickitung import Lickitung
from Koffing import Koffing
from Weezing import Weezing
from Rhyhorn import Rhyhorn
from Rhydon import Rhydon
from Chansey import Chansey
from Tangela import Tangela
from Kangaskhan import Kangaskhan
from Horsea import Horsea
from Seadra import Seadra
from Goldeen import Goldeen
from Seaking import Seaking
from Staryu import Staryu
from Starmie import Starmie
from Mr_Mime import Mr_Mime
from Scyther import Scyther
from Jynx import Jynx
from Electabuzz import Electabuzz
from Magmar import Magmar
from Pinsir import Pinsir
from Tauros import Tauros
from Magikarp import Magikarp
from Gyarados import Gyarados
from Lapras import Lapras
from Ditto import Ditto
from Eevee import Eevee
from Vaporeon import Vaporeon
from Jolteon import Jolteon
from Flareon import Flareon
from Porygon import Porygon
from Omanyte import Omanyte
from Omastar import Omastar
from Kabuto import Kabuto
from Kabutops import Kabutops
from Aerodactyl import Aerodactyl
from Snorlax import Snorlax
from Articuno import Articuno
from Zapdos import Zapdos
from Moltres import Moltres
from Dratini import Dratini
from Dragonair import Dragonair
from Dragonite import Dragonite
from Mewtwo import Mewtwo
from Mew import Mew
from Missingno import Missingno
